THUVIEN_CNPMNC_TH/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using THUVIEN_CNPMNC_TH.Models;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace THUVIEN_CNPMNC_TH.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        LIBRARY_FINALEntities1 database = new LIBRARY_FINALEntities1();

        private string GenerateNextMaSach()
        {
            string defaultMaSach = "S001";
            string nextMaSach = defaultMaSach;

            while (database.Books.Any(b => b.MaSach == nextMaSach))
            {
                string numericPart = nextMaSach.Substring(1);

                if (int.TryParse(numericPart, out int numericValue))
                {
                    numericValue++;
                    nextMaSach = $"S{numericValue:D3}";
                }
                else
                {
                    nextMaSach = defaultMaSach;
                    break;
                }
            }

            return nextMaSach;
        }

        public ActionResult QLSach()
        {
            return View();
        }

        public ActionResult QLSTTL(string maTheLoai)
        {
            var theLoais = database.TheLoais.ToList();
            if (string.IsNullOrEmpty(maTheLoai))
            {
                maTheLoai = theLoais.FirstOrDefault()?.MaTheLoai;
            }
            var books = database.Books.Where(b => b.MaTheLoai == maTheLoai).ToList();
            ViewBag.Books = books;
            ViewBag.SelectedTheLoai = maTheLoai;

            return View(theLoais);
        }

        public ActionResult AddBookView()
        {
            var tenSachList = database.PhieuNhaps.Select(pn => pn.TenSach).Distinct().ToList();
            ViewBag.TenSachList = new SelectList(tenSachList);

            ViewBag.TheLoaiList = new SelectList(database.TheLoais, "MaTheLoai", "TenTheLoai");
            ViewBag.NhaXuatBanList = new SelectList(database.NhaXuatBans, "MaNXB", "TenNXB");

            var nextMaSach = GenerateNextMaSach();
            var book = new Book { MaSach = nextMaSach };

            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddBookView(Book book, HttpPostedFileBase imageFile, string selectedTenSach, string maTheLoai, string maNXB, bool? chooseTheLoai, bool? chooseMaNXB)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    book.TrungBay = false;
                    book.LuotMuonTra = 0;

                    if (!chooseTheLoai.HasValue)
                    {
                        book.MaTheLoai = maTheLoai;
                    }
                    if (!chooseMaNXB.HasValue)
                    {
                        book.MaNXB = maNXB;
                    }

                    book.MaSach = GenerateNextMaSach();
                    book.TenSach = selectedTenSach;

                    // Query the quantity of selectedTenSach from PhieuNhap
                    int quantityInPhieuNhap = database.PhieuNhaps
                        .Where(pn => pn.TenSach == selectedTenSach)
                        .Sum(pn => pn.SoLuong) ?? 0;

                    if (book.SoLuong <= quantityInPhieuNhap)
                    {
                        if (imageFile != null && imageFile.ContentLength > 0)
                        {
                            string fileName = Path.GetFileName(imageFile.FileName);
                            string filePath = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                            imageFile.SaveAs(filePath);
                            book.HinhAnh = "~/Content/Images/" + fileName;
                        }
                        database.Books.Add(book);
                        database.SaveChanges();

                        return RedirectToAction("QLSach");
                    }
                    else
                    {
                        ModelState.AddModelError("SoLuong", "Số lượng sách không được vượt quá " + quantityInPhieuNhap);
                    }
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error");
                }
            }
            var tenSachList = database.PhieuNhaps.Select(pn => pn.TenSach).Distinct().ToList();
            ViewBag.TenSachList = new SelectList(tenSachList);
            ViewBag.TheLoaiList = new SelectList(database.TheLoais, "MaTheLoai", "TenTheLoai");
            ViewBag.NhaXuatBanList = new SelectList(database.NhaXuatBans, "MaNXB", "TenNXB");

            return View(book);
        }



        // Rest of your controller actions...

        public ActionResult DeleteBookView()
        {
            return View(database.Books.ToList());
        }

        [HttpPost]
        public ActionResult DeleteBook(string MaSach)
        {
            var book = database.Books.FirstOrDefault(b => b.MaSach == MaSach);
            if (book != null)
            {
                database.Books.Remove(book);
                database.SaveChanges();
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false });
            }
        }


        public ActionResult ArrayBookView()
        {
            var books = database.Books.ToList();
            foreach (var book in books)
            {
                if (book.SoLuong <= 3)
                {
                    book.TrungBay = false;
                }
            }
            database.SaveChanges();

            return View(books);
        }

        public ActionResult DetailBookView(string MaSach)
        {
            var book = database.Books.FirstOrDefault(s => s.MaSach == MaSach);
            return View(book);
        }

        [HttpGet]
        public ActionResult EditBookView(string MaSach)
        {
            var book = database.Books.FirstOrDefault(b => b.MaSach == MaSach);
            if (book != null)
            {
                ViewBag.TheLoaiList = new SelectList(database.TheLoais, "MaTheLoai", "TenTheLoai", book.MaTheLoai);
                ViewBag.NhaXuatBanList = new SelectList(database.NhaXuatBans, "MaNXB", "TenNXB", book.MaNXB);
                return View(book);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBook(Book book, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Book existingBook = database.Books.FirstOrDefault(b => b.MaSach == book.MaSach);
                    if (existingBook != null)
                    {
                        existingBook.TenSach = book.TenSach;
                        existingBook.MaTheLoai = book.MaTheLoai;
                        existingBook.MaNXB = book.MaNXB;
                        existingBook.TacGia = book.TacGia;
                        existingBook.SoLuong = book.SoLuong;
                        existingBook.NamXuatBan = book.NamXuatBan;
                        existingBook.MoTa = book.MoTa;

                        if (imageFile != null && imageFile.ContentLength > 0)
                        {
                            string fileName = Path.GetFileName(imageFile.FileName);
                            string filePath = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                            imageFile.SaveAs(filePath);
                            existingBook.HinhAnh = "~/Content/Images/" + fileName;
                        }

                        database.SaveChanges();
                    }

                    return RedirectToAction("QLSach");
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error");
                }
            }

            ViewBag.TheLoaiList = new SelectList(database.TheLoais, "MaTheLoai", "TenTheLoai", book.MaTheLoai);
            ViewBag.NhaXuatBanList = new SelectList(database.NhaXuatBans, "MaNXB", "TenNXB", book.MaNXB);

            return View(book);
        }

        [HttpPost]
        public ActionResult UpdateTrungBay(string maSach, bool isChecked)
        {
            try
            {
                var book = database.Books.FirstOrDefault(b => b.MaSach == maSach);
                if (book != null)
                {
                    book.TrungBay = isChecked;
                    database.SaveChanges();
                    return Json(new { success = true });
                }
                else
                {
                    return Json(new { success = false });
                }
            }
            catch (Exception ex)
            {
                // Handle any exceptions here
                return Json(new { success = false });
            }
        }


        //////////////////////////


        public ActionResult QLTheLoaiView()
        {
            return View(database.TheLoais.ToList());
        }

        private string GenerateNextMaTheLoai()
        {
            string defaultMaTheLoai = "TL001";
            string nextMaTheLoai = defaultMaTheLoai;

            while (database.TheLoais.Any(tl => tl.MaTheLoai == nextMaTheLoai))
            {
                string numericPart = nextMaTheLoai.Substring(2);

                if (int.TryParse(numericPart, out int numericValue))
                {
                    numericValue++;
                    nextMaTheLoai = $"TL{numericValue:D3}";
                }
                else
                {
                    nextMaTheLoai = defaultMaTheLoai;
                    break;
                }
            }

            return nextMaTheLoai;
        }

        public ActionResult AddTheLoai()
        {

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/AddBookView.cshtml
@model THUVIEN_CNPMNC_TH.Models.Book
@{
    ViewBag.Title = "AddBookView";
}


<link href="~/Areas/Admin/Content/css/SanPham/AddBookView.css" rel="stylesheet" />
<script src="/path/or/uri/to/tinymce.min.js" referrerpolicy="origin"></script>
<script type="text/javascript"
        src='https://cdn.tiny.cloud/1/x3qgdtb5ciacelhye5u7rzmlra9rscq605jima6m82o8jm37/tinymce/6/tinymce.min.js'
        referrerpolicy="origin">
</script>
<div class="container">

    <h1>THÊM MỚI SÁCH</h1>

    @using (Html.BeginForm("AddBookView", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.Label("Tên sách:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.DropDownList("selectedTenSach", (SelectList)ViewBag.TenSachList, "Chọn tên sách", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.MaTheLoai, "Mã thể loại:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    <input type="checkbox" id="chooseTheLoai" name="chooseTheLoai" /> Chọn từ danh sách
                    <br />
                    <div id="theLoaiDropdown" style="display:none;">
                        @Html.DropDownList("MaTheLoai", ViewBag.TheLoaiList as SelectList, "Chọn thể loại", new { @class = "form-control" })
                    </div>
                    <div id="theLoaiTextBox">
                        @Html.TextBoxFor(model => model.MaTheLoai, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaTheLoai)
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNXB, "Mã nhà xuất bản:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    <input type="checkbox" id="chooseMaNXB" name="chooseMaNXB" /> Chọn từ danh sách
                    <br />
                    <div id="maNXBDropdown" style="display:none;">
                        @Html.DropDownList("MaNXB", ViewBag.NhaXuatBanList as SelectList, "Chọn nhà xuất bản", new { @class = "form-control" })
                    </div>
                    <div id="maNXBTextBox">
                        @Html.TextBoxFor(model => model.MaNXB, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaNXB)
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TacGia, "Tác giả:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SoLuong, "Số lượng:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control input-quantity" } })
                    @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NamXuatBan, "Năm xuất bản:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.NamXuatBan, new { @class = "form-control input-date", type = "date" })
                    @Html.ValidationMessageFor(model => model.NamXuatBan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MoTa, "Mô tả:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextAreaFor(model => model.MoTa, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnh, "Hình ảnh:")
                <input type="file" name="imageFile" id="imageFile" />
                <img id="previewImage" src="#" alt="Ảnh sách" style="max-width: 300px; max-height: 300px; display: none;" />
                @Html.ValidationMessageFor(model => model.HinhAnh)
            </div>


            <input type="submit" value="Thêm Mới " class="btn btn-default" />

        </div>
    }

    <div>
        @Html.ActionLink("Trở lại", "QLSach")
    </div>


</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    tinymce.init({
        selector: 'textarea',
        language: 'vi_VN',
        plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
    });
    tinymce.init(editor_config);
</script>
<script>
    $(document).ready(function () {
        $("#chooseTheLoai").change(function () {
            if (this.checked) {
                $("#theLoaiDropdown").show();
                $("#theLoaiTextBox").hide();
            } else {
                $("#theLoaiDropdown").hide();
                $("#theLoaiTextBox").show();
            }
        });

        $("#chooseMaNXB").change(function () {
            if (this.checked) {
                $("#maNXBDropdown").show();
                $("#maNXBTextBox").hide();
            } else {
                $("#maNXBDropdown").hide();
                $("#maNXBTextBox").show();
            }
        });

        // Thêm sự kiện thay đổi vào trường input file
        $("#imageFile").change(function () {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#previewImage").attr("src", e.target.result);
                    $("#previewImage").show();
                };
                reader.readAsDataURL(input.files[0]);
            }
        });
    });

    $("#imageFile").change(function () {
        if (ModelState.isValid) { // Kiểm tra ModelState trước khi thực hiện mã JavaScript
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#previewImage").attr("src", e.target.result);
                    $("#previewImage").show();
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    });

    tinymce.init({
        selector: '.tinymce-editor',
        height: 300,  // Điều chỉnh chiều cao theo ý muốn
    });
</script>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/AddTheLoai.cshtml
@model THUVIEN_CNPMNC_TH.Models.TheLoai

@{
    ViewBag.Title = "AddTheLoai";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link href="~/Areas/Admin/Content/css/SanPham/AddBookView.css" rel="stylesheet" />
<h1>THÊM THỂ LOẠI </h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.TenTheLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTheLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTheLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="submit" value="Thêm Mới " class="btn btn-default" />
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/DeleteBookView.cshtml
@{
    ViewBag.Title = "DeleteBookView";
}

<link href="~/Areas/Admin/Content/css/SanPham/DeleteBookView.css" rel="stylesheet" />

<div class="Content">
    <h1> XÓA SÁCH </h1>
    <div class="search-container">
        <input type="text" id="searchInput" placeholder="Hãy nhập tên sách bạn muốn tìm kiếm......">
    </div>
    <table>
        <thead>
            <tr>
                <th>Mã sách</th>
                <th>Tên sách</th>
                <th>Ảnh</th>
                <th>Tác giả</th>
                <th>Số lượng</th>
                <th>Nhà xuất bản</th>
                <th>Chỉnh sửa</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.MaSach</td>
                    <td>@book.TenSach</td>
                    <td><img src="@Url.Content(book.HinhAnh)" alt="Book Image" /></td>
                    <td>@book.TacGia</td>
                    <td>@book.SoLuong</td>
                    <td>@book.NhaXuatBan.TenNXB</td>
                    <td>
                        <a href="#" class="action-btn delete-btn" data-book-id="@book.MaSach">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="custom-modal" id="confirmationModal">
        <div class="modal-content">
            <h2>Xác nhận xóa sách</h2>
            <p>Bạn có muốn xóa sách này không?</p>
            <div class="modal-buttons">
                <button id="confirmDelete">Có </button>
                <button id="cancelDelete">Không</button>
            </div>
        </div>
    </div>



</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function removeDiacritics(text) {
        return text.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    }

    $(document).ready(function () {
        $(".delete-btn").on("click", function () {
            var bookId = $(this).data("book-id");
            var confirmationModal = $("#confirmationModal");

            // Hiển thị modal
            confirmationModal.css("display", "flex");

            // Xử lý nút Xác nhận
            $("#confirmDelete").on("click", function () {
                $.ajax({
                    url: '/Admin/SanPham/DeleteBook',
                    type: 'POST',
                    data: { MaSach: bookId },
                    success: function (data) {
                        if (data.success) {
                            location.reload();
                        } else {
                            alert("Xóa thất bại.");
                        }
                    },
                    error: function () {
                        alert("Đã xảy ra lỗi trong khi xử lý yêu cầu của bạn.");
                    }
                });

                // Đóng modal sau khi xác nhận
                confirmationModal.hide();
            });

            // Xử lý nút Hủy
            $("#cancelDelete").on("click", function () {
                // Đóng modal khi hủy
                confirmationModal.hide();
            });
        });


        $("#searchInput").on("input", function () {
            var searchText = removeDiacritics($(this).val().toLowerCase());
            $("tbody tr").each(function () {
                var bookName = removeDiacritics($(this).find("td:eq(1)").text().toLowerCase());
                if (bookName.includes(searchText)) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        });
    });
</script>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/DetailBookView.cshtml
<link href="~/Areas/Admin/Content/css/SanPham/Detail.css" rel="stylesheet" />
@model THUVIEN_CNPMNC_TH.Models.Book
<h1>CHI TIẾT SÁCH</h1>
<div class="row book-details">
    <div class="col-4 book-image">
        <img src="@Url.Content(Model.HinhAnh)" alt="Book Image" />
        <p class="mota">Mô tả:</p>
    </div>
    <div class="col-lg-8 book-info">
        <table>
            <tbody>
                <tr>
                    <th>Tên sách: @Html.DisplayFor(model => model.TenSach)</th>
                </tr>
                <tr>
                    <th>Mã thể loại: @Html.DisplayFor(model => model.TheLoai.MaTheLoai)</th>
                </tr>
                <tr>
                    <th>Tên thể loại: @Html.DisplayFor(model => model.TheLoai.TenTheLoai)</th>
                </tr>
                <tr>
                    <th>Năm xuất bản: @(Model.NamXuatBan.HasValue ? Model.NamXuatBan.Value.ToString("yyyy") : "")</th>
                </tr>
                <tr>
                    <th>Mã nhà xuất bản: @Html.DisplayFor(model => model.NhaXuatBan.MaNXB)</th>
                </tr>
                <tr>
                    <th>Nhà xuất bản: @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)</th>
                </tr>
            </tbody>
        </table>
    </div>
    <span class="col-lg-12"> @Html.DisplayFor(model => model.MoTa)</span>
</div>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/EditBookView.cshtml
@model THUVIEN_CNPMNC_TH.Models.Book
@{
    ViewBag.Title = "EditBookView";
}

<link href="~/Areas/Admin/Content/css/SanPham/Editbook.css" rel="stylesheet" />

<div class="container">
    <h1>SỬA SÁCH</h1>
    @using (Html.BeginForm("EditBook", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MaSach)

        <label for="namebook">Tên sách:</label><br>
        @Html.TextBoxFor(model => model.TenSach, new { id = "namebook" })<br>

        <label for="author">Tác giả:</label><br>
        @Html.TextBoxFor(model => model.TacGia, new { id = "author" })<br>

        <label for="publisher">Nhà xuất bản:</label><br>
        @Html.DropDownListFor(model => model.MaNXB, ViewBag.NhaXuatBanList as SelectList, "-- Chọn Nhà xuất bản --", new { id = "publisher" })<br>

        <label for="year">Năm xuất bản:</label><br>
        @Html.TextBoxFor(model => model.NamXuatBan, new { id = "year" })<br>

        <label for="quantity">Số lượng:</label><br>
        @Html.TextBoxFor(model => model.SoLuong, new { id = "quantity" })<br>

        <label for="image">Hình ảnh:</label><br>
        <input type="file" id="image" name="image">
        <img id="previewImage" src="@Url.Content(Model.HinhAnh)" alt="Hình ảnh sẽ được hiển thị ở đây"><br><br>

        <input type="submit" value="Lưu">
    }
    <script>
        // Lắng nghe sự kiện khi người dùng chọn tệp hình ảnh
        document.getElementById("image").addEventListener("change", function () {
            var previewImage = document.getElementById("previewImage");
            var fileInput = this;
            if (fileInput.files && fileInput.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    // Hiển thị hình ảnh đã chọn
                    previewImage.src = e.target.result;
                    previewImage.style.display = "block"; // Hiển thị hình ảnh sau khi đã chọn tệp
                };
                reader.readAsDataURL(fileInput.files[0]);
            }
        });
    </script>
</div>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/QLSTTL.cshtml
@model IEnumerable<THUVIEN_CNPMNC_TH.Models.TheLoai>

@{
    ViewBag.Title = "Quản lý sách theo thể loại";
}
<link href="~/Areas/Admin/Content/css/SanPham/QLSTTL.css" rel="stylesheet" />

<div class="content-book">
    <div class="selected">
        <h1>QUẢN LÝ SÁCH THEO THỂ LOẠI</h1>

        @using (Html.BeginForm("QLSTTL", "SanPham", FormMethod.Get))
        {
            <div class="form-group">
                <label class="label" for="maTheLoai">CHỌN THỂ LOẠI:</label>
                <select name="maTheLoai" id="maTheLoai" onchange="this.form.submit()">
                    @foreach (var theLoai in Model)
                    {
                        <option value="@theLoai.MaTheLoai" @(ViewBag.SelectedTheLoai == theLoai.MaTheLoai ? "selected" : "")>@theLoai.TenTheLoai</option>
                    }
                </select>
            </div>
        }
    </div>

    @if (ViewBag.Books != null)
    {
        <table>
            <thead>
                <tr>
                    <th>Tên sách</th>
                    <th>Ảnh</th>
                    <th>Tác giả</th>
                    <th>Năm xuất bản</th>
                    <th>Số lượng</th>
                    <th>Nhà xuất bản</th>
                    <th>Chi tiết</th>
                    <!-- Thêm các cột khác tùy ý -->
                </tr>
            </thead>
            <tbody>
                @foreach (var book in ViewBag.Books)
                {
                    <tr>
                        <td>@book.TenSach</td>
                        <td><img src="@Url.Content(book.HinhAnh)" alt="Book Image" /></td>
                        <td>@book.TacGia</td>
                        <td>@book.NamXuatBan.ToString("dd/MM/yyyy")</td>
                        <td>@book.SoLuong</td>
                        <td>@book.NhaXuatBan.TenNXB</td>
                        <td>
                            <a href="/Admin/SanPham/DetailBookView?MaSach=@book.MaSach" class="action-btn detail-btn">Details</a>

                        </td>

                        <!-- Thêm các cột khác tùy ý -->
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/SanPham/QLSach.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>title</title>
    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">*@
    <link rel="stylesheet" href="~/Areas/Admin/Content/css/SanPham/IndexQLS.css">

<body>
    <div class="container quanlysach">
        <p class="Title">QUẢN LÝ SÁCH</p>
        <div class="row">
            <div class="col-3 ">
                <div class="imgaddbook">
                    <img src="~/Content/Images/addbook.png" alt="Thêm sách">
                    <form method="GET" action="@Url.Action("AddBookView", "SanPham")">
                        <input type="submit" value="Thêm sách" />
                    </form>

                </div>
            </div>
            <div class="col-3  ">
                <div class="imgeditbook">
                    <img src="~/Content/Images/editbook.png" alt="Sửa sách">
                    <form method="GET" action="@Url.Action("ArrayBookView","SanPham")">
                        <input type="submit" value="Xem & Sửa sách" />
                    </form>
                </div>
            </div>
            <div class="col-3 ">
                <div class="dltbook">
                    <img src="~/Content/Images/deletebook.png" alt="Xóa sách">
                    <form method="GET" action="@Url.Action("DeleteBookView", "SanPham")">
                        <input type="submit" value="Xóa sách" />
                    </form>
                </div>
            </div>
        </div>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>