THUVIEN_CNPMNC_TH/Models/TheDocGia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIEN_CNPMNC_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheDocGia
    {
        public string MaThe { get; set; }
        public string MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}

THUVIEN_CNPMNC_TH/Areas/Admin/Controllers/TheDocGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using THUVIEN_CNPMNC_TH.Models;

namespace THUVIEN_CNPMNC_TH.Areas.Admin.Controllers
{
    public class TheDocGiaController : Controller
    {
        // GET: Admin/TheDocGia
        LIBRARY_FINALEntities1 database = new LIBRARY_FINALEntities1();
        public ActionResult QLTheDocGia()
        {
            var viewModel = new ViewModel
            {
                TheDocGias = database.TheDocGias.ToList(),
                // Other properties need to be populated here as well
            };

            return View(viewModel);
        }

        public ActionResult ThemTheDocGia()
        {
            var listTenDocGia = database.DocGias.Select(dg => new { dg.TenDocGia, dg.MaDocGia }).ToList();
            ViewBag.ListTenDocGia = new SelectList(listTenDocGia, "MaDocGia", "TenDocGia");

            return View();
        }

        [HttpPost]
        public ActionResult LuuTheDocGia(TheDocGia newTheDocGia, int HanSuDungOption)
        {
            if (ModelState.IsValid)
            {
                if (newTheDocGia.NgayCap > DateTime.Now)
                {
                    ModelState.AddModelError("NgayCap", "Ngày cấp không được lớn hơn ngày hiện tại.");
                    var listTenDocGia = database.DocGias.Select(dg => new { dg.TenDocGia, dg.MaDocGia }).ToList();
                    ViewBag.ListTenDocGia = new SelectList(listTenDocGia, "MaDocGia", "TenDocGia");
                    return View("ThemTheDocGia", newTheDocGia);
                }

                // Tính toán ngày hết hạn dựa trên thời gian đã chọn và ngày cấp
                switch (HanSuDungOption)
                {
                    case 3:
                        newTheDocGia.HanSuDung = newTheDocGia.NgayCap.Value.AddMonths(3);
                        break;
                    case 6:
                        newTheDocGia.HanSuDung = newTheDocGia.NgayCap.Value.AddMonths(6);
                        break;
                    case 12:
                        newTheDocGia.HanSuDung = newTheDocGia.NgayCap.Value.AddYears(1);
                        break;
                }

                // Tự động sinh mã thẻ mới
                newTheDocGia.MaThe = GenerateNextMaThe();
                database.TheDocGias.Add(newTheDocGia);
                database.SaveChanges();
                return RedirectToAction("QLTheDocGia");
            }
            return View("ThemTheDocGia", newTheDocGia);
        }


        private string GenerateNextMaThe()
        {
            string defaultMaThe = "T001";
            string nextMaThe = defaultMaThe;

            // Kiểm tra xem MaThe đã tồn tại trong cơ sở dữ liệu hay chưa
            while (database.TheDocGias.Any(t => t.MaThe == nextMaThe))
            {
                // Tách phần số hậu tố ra khỏi MaThe
                string numericPart = nextMaThe.Substring(1);

                // Tăng giá trị số lên 1 và cập nhật MaThe mới
                if (int.TryParse(numericPart, out int numericValue))
                {
                    numericValue++;
                    nextMaThe = $"T{numericValue:D03}";
                }
                else
                {
                    // Nếu không thể phân tích phần số hậu tố, trở lại mã mặc định "T01"
                    nextMaThe = defaultMaThe;
                    break;
                }
            }

            return nextMaThe;
        }



        [HttpPost]
        public ActionResult XoaTheDocGia(string maThe)
        {
            if (string.IsNullOrEmpty(maThe))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var theDocGia = database.TheDocGias.FirstOrDefault(t => t.MaThe == maThe);
            if (theDocGia == null)
            {
                return HttpNotFound();
            }

            database.TheDocGias.Remove(theDocGia);
            database.SaveChanges();

            return RedirectToAction("QLTheDocGia");
        }
    }
}

THUVIEN_CNPMNC_TH/Areas/Admin/Views/TheDocGia/QLTheDocGia.cshtml
@model THUVIEN_CNPMNC_TH.Models.ViewModel

@{
    ViewBag.Title = "QLTheDocGia";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<link href="~/Areas/Admin/Content/css/TheDocGia/QLTheDocGia.css" rel="stylesheet" />
<div class="container">
    <h1>QUẢN LÝ THẺ ĐỘC GIẢ</h1>
    <table class="table">
        <tr>
            <th>Mã Thẻ</th>
            <th>Mã Độc Giả</th>
            <th>Ngày Cấp</th>
            <th>Hạn Sử Dụng</th>
            <th></th>
        </tr>
        @foreach (var theDocGia in Model.TheDocGias)
        {
            <tr>
                <td>@theDocGia.MaThe</td>
                <td>@theDocGia.MaDocGia</td>
                <td>@(theDocGia.NgayCap.HasValue ? theDocGia.NgayCap.Value.ToString("dd/MM/yyyy") : "")</td>
                <td>@(theDocGia.HanSuDung.HasValue ? theDocGia.HanSuDung.Value.ToString("dd/MM/yyyy") : "")</td>
                <td>
                    @using (Html.BeginForm("XoaTheDocGia", "TheDocGia", new { maThe = theDocGia.MaThe }, FormMethod.Post, new { onsubmit = "return confirm('Bạn có chắc muốn xóa thẻ độc giả này?');" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Xóa" class="btn btn-danger" />
                    }
                </td>
            </tr>
        }

    </table>
    <a href="@Url.Action("ThemTheDocGia", "TheDocGia")" class="btn-add">Thêm thẻ độc giả</a>

</div>

<style>
    .btn-add {
        background-color: Green;
        color: white;
        border: none;
        padding: 10px 10px;
        border-radius: 5px;
        cursor: pointer;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
    }

    .btn-add:hover {
        background-color: forestgreen;
        color: white;
        text-decoration:none;
    }
</style>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/TheDocGia/ThemTheDocGia.cshtml
@model THUVIEN_CNPMNC_TH.Models.TheDocGia
@{
    ViewBag.Title = "Thêm Thẻ Độc Giả";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<link href="~/Areas/Admin/Content/css/TheDocGia/ThemTDG.css" rel="stylesheet" />
<div class="container">
    <h1>THÊM THẺ ĐỘC GIẢ</h1>
    @using (Html.BeginForm("LuuTheDocGia", "TheDocGia", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <div class="form-group">
            @Html.LabelFor(model => model.MaDocGia, "Tên độc giả:", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("MaDocGia", ViewBag.ListTenDocGia as SelectList, "-- Chọn độc giả --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDocGia, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCap, "Ngày cấp:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.NgayCap, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.NgayCap, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HanSuDung, "Hạn sử dụng:", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("HanSuDungOption", new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "3 tháng", Value = "3" },
                new SelectListItem { Text = "6 tháng", Value = "6" },
                new SelectListItem { Text = "1 năm", Value = "12" }
            }, "Value", "Text"), "-- Chọn thời gian hạn sử dụng --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.HanSuDung, "", new { @class = "text-danger" })
        </div>



        <input type="submit" value="Thêm" class="btn btn-primary" />
    }
</div>