THUVIEN_CNPMNC_TH/Models/DocGia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIEN_CNPMNC_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.PhieuMuonTras = new HashSet<PhieuMuonTra>();
            this.TheDocGias = new HashSet<TheDocGia>();
        }
    
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public Nullable<int> Roles { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuonTra> PhieuMuonTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheDocGia> TheDocGias { get; set; }
    }
}

THUVIEN_CNPMNC_TH/Areas/Admin/Controllers/DocGiaController.cs
using THUVIEN_CNPMNC_TH.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace THUVIEN_CNPMNC_TH.Areas.Admin.Controllers
{
    public class DocGiaController : Controller
    {
        LIBRARY_FINALEntities1 database = new LIBRARY_FINALEntities1();

        // GET: Admin/DocGia
        public ActionResult QLDocGia()
        {
            return View(database.DocGias.ToList());
        }

        public ActionResult EditDocGia(string maDocGia)
        {
            var docGia = database.DocGias.FirstOrDefault(d => d.MaDocGia == maDocGia);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            return View(docGia);
        }

        [HttpPost]
        public ActionResult SaveEdit(DocGia editedDocGia)
        {
            var existingDocGia = database.DocGias.FirstOrDefault(d => d.MaDocGia == editedDocGia.MaDocGia);
            if (existingDocGia == null)
            {
                return HttpNotFound();
            }

            existingDocGia.TenDocGia = editedDocGia.TenDocGia;
            existingDocGia.NgaySinh = editedDocGia.NgaySinh;
            existingDocGia.DiaChi = editedDocGia.DiaChi;
            existingDocGia.GioiTinh = editedDocGia.GioiTinh;
            existingDocGia.SoDienThoai = editedDocGia.SoDienThoai;
            database.SaveChanges();
            return RedirectToAction("QLDocGia");
        }

        [HttpPost]
        public ActionResult DeleteDocGia(string maDocGia)
        {
            var docGia = database.DocGias.FirstOrDefault(d => d.MaDocGia == maDocGia);
            if (docGia != null)
            {
                database.DocGias.Remove(docGia);
                database.SaveChanges();
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false });
            }
        }

        public ActionResult AddDocGia()
        {
            return View();
        }

        // POST: Admin/DocGia/SaveAdd
        [HttpPost]
        public ActionResult SaveAdd(DocGia newDocGia)
        {
            if (ModelState.IsValid)
            {
                if (newDocGia.NgaySinh.HasValue)
                {
                    
                    int currentYear = DateTime.Now.Year;

                    // Lấy năm sinh từ ngày sinh
                    int birthYear = newDocGia.NgaySinh.Value.Year;

                    // Tính tuổi bằng cách lấy hiện tại trừ đi năm sinh
                    int age = currentYear - birthYear;

                    // Kiểm tra tuổi phải trên 12 tuổi so với hiện tại
                    if (age < 12)
                    {
                        ModelState.AddModelError("NgaySinh", "Tuổi của độc giả phải trên 12 tuổi. Vui lòng nhập lại ngày sinh.");
                        return View("AddDocGia", newDocGia);
                    }
                }
                else
                {
                    ModelState.AddModelError("NgaySinh", "Ngày sinh không hợp lệ. Vui lòng nhập lại ngày sinh.");
                    return View("AddDocGia", newDocGia);
                }
                newDocGia.MaDocGia = GenerateNextMaDocGia();

                database.DocGias.Add(newDocGia);
                database.SaveChanges();
                return RedirectToAction("QLDocGia");
            }
            return View("AddDocGia", newDocGia);
        }



        // Helper method to generate the next MaDocGia
        private string GenerateNextMaDocGia()
        {
            string defaultMaDocGia = "DG001";
            string nextMaDocGia = defaultMaDocGia;

            // Kiểm tra xem MaDocGia đã tồn tại trong cơ sở dữ liệu hay chưa
            while (database.DocGias.Any(d => d.MaDocGia == nextMaDocGia))
            {
                // Tách phần số hậu tố ra khỏi MaDocGia
                string numericPart = nextMaDocGia.Substring(2);

                // Tăng giá trị số lên 1 và cập nhật MaDocGia mới
                if (int.TryParse(numericPart, out int numericValue))
                {
                    numericValue++;
                    nextMaDocGia = string.Format("DG{0:D3}", numericValue);
                }
                else
                {
                    // Nếu không thể phân tích phần số hậu tố, trở lại MaDocGia mặc định "DG001"
                    nextMaDocGia = defaultMaDocGia;
                    break;
                }
            }

            return nextMaDocGia;
        }
    }
}

THUVIEN_CNPMNC_TH/Areas/Admin/Views/DocGia/AddDocGia.cshtml
@{
    ViewBag.Title = "AddDocGia";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model THUVIEN_CNPMNC_TH.Models.DocGia

<link href="~/Areas/Admin/Content/css/DocGia/AddDG.css" rel="stylesheet" />

<div class="container">
    <h1>THÊM ĐỘC GIẢ </h1>
    @using (Html.BeginForm("SaveAdd", "DocGia", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(model => model.TenDocGia, "Tên độc giả:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.TenDocGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenDocGia, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, "Ngày sinh:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, "Email:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDienThoai, "Số điện thoại:", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
        </div>

        <!-- Add more form fields for other properties of DocGia entity as needed -->

        <input type="submit" value="Thêm" class="btn btn-primary" />
    }
</div>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/DocGia/EditDocGia.cshtml
@{
    ViewBag.Title = "EditDocGia";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@model THUVIEN_CNPMNC_TH.Models.DocGia
<link href="~/Areas/Admin/Content/css/DocGia/EditDG.css" rel="stylesheet" />


<div class="container">
    <h1>CHỈNH SỬA ĐỘC GIẢ</h1>
    <form method="post" action="/Admin/DocGia/SaveEdit">
        <input type="hidden" name="MaDocGia" value="@Model.MaDocGia" />
        <div>
            <label for="TenDocGia">Tên DG:</label>
            <input type="text" name="TenDocGia" value="@Model.TenDocGia" />
        </div>
        <div>
            <label for="GioiTinh">Giới tính:</label>
            <select name="GioiTinh" id="GioiTinhSelect">
                <option value="Nam">Nam</option>
                <option value="Nữ">Nữ</option>
            </select>
        </div>

        <div>
            <label for="SDT">Số điện thoại:</label>
            <input type="text" name="SDT" value="@Model.SoDienThoai" />
        </div>
        <div>
            <label for="NgaySinh">Ngày sinh:</label>
            <input type="date" name="NgaySinh" value="@Model.NgaySinh?.ToString(" yyyy-MM-dd")" />
        </div>
        <div>
            <label for="DiaChi">Địa chỉ :</label>
            <input type="text" name="DiaChi" value="@Model.DiaChi" />
        </div>
        <!-- Add more input fields for other properties -->
        <div>
            <input class="save" type="submit" value="Save" />
            <a class="cancel" href="/Admin/DocGia/QLDocGia">Cancel</a>
        </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        var gioiTinhValue = "@Model.GioiTinh"; // Giá trị mô hình

        // Đặt giá trị mặc định cho trường chọn dựa trên giá trị mô hình
        $("#GioiTinhSelect").val(gioiTinhValue);
    });
</script>

THUVIEN_CNPMNC_TH/Areas/Admin/Views/DocGia/QLDocGia.cshtml
@model IEnumerable<THUVIEN_CNPMNC_TH.Models.DocGia>

@{
    ViewBag.Title = "QLDocGia";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<link href="~/Areas/Admin/Content/css/DocGia/QLDocGia.css" rel="stylesheet" />
<div class="container-fluid">
    <h1>QUẢN LÝ ĐỘC GIẢ</h1>
    <table>
        <thead>
            <tr>
                <th>Mã DG</th>
                <th>Tên DG</th>
                <th>Ngày sinh</th>
                <th>Giới tính</th>
                <th>SDT</th>
                <th>Email</th>
                <th>Địa chỉ</th>
                <th>Chỉnh sửa</th>
                <!-- Thêm các cột khác tùy ý -->
            </tr>
        </thead>
        <tbody>
            @foreach (var docGia in Model)
            {
                <tr>
                    <td>@docGia.MaDocGia</td>
                    <td>@docGia.TenDocGia</td>
                    <td>@(docGia.NgaySinh.HasValue ? docGia.NgaySinh.Value.ToString("dd/MM/yyyy") : "")</td>
                    <td>@docGia.GioiTinh</td>
                    <td>@docGia.SoDienThoai</td>
                    <td>@docGia.Email</td>
                    <td>@docGia.DiaChi</td>
                    <td>
                        <a href="@Url.Action("EditDocGia", "DocGia", new { maDocGia = docGia.MaDocGia })" class="action-btn "> Sửa </a>
                        <a href="#" class="action-btn delete-btn" data-docgia-id="@docGia.MaDocGia">Xóa</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a href="/Admin/DocGia/AddDocGia" class=btn-add>Thêm độc giả</a>

    <div class="custom-modal" id="confirmationModal">
        <div class="modal-content">
            <h2>Xác nhận xóa độc giả</h2>
            <p>Bạn có muốn xóa độc giả này không?</p>
            <div class="modal-buttons">
                <button id="confirmDelete">Có </button>
                <button id="cancelDelete">Không</button>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function removeDiacritics(text) {
        return text.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    }

    $(document).ready(function () {
        $(".delete-btn").on("click", function () {
            var docgiaid = $(this).data("docgia-id");
            var confirmationModal = $("#confirmationModal");
            confirmationModal.css("display", "flex");
            $("#confirmDelete").on("click", function () {
                $.ajax({
                    url: '/Admin/DocGia/DeleteDocGia',
                    type: 'POST',
                    data: { MaDocGia: docgiaid },
                    success: function (data) {
                        if (data.success) {
                            location.reload();
                        } else {
                            alert("Xóa thất bại.");
                        }
                    },
                    error: function () {
                        alert("Đã xảy ra lỗi trong khi xử lý yêu cầu của bạn.");
                    }
                });

                confirmationModal.hide();
            });
            // Xử lý nút Hủy
            $("#cancelDelete").on("click", function () {
                confirmationModal.hide();
            });
        });
    });

</script>